import localFont from "next/font/local";
import "./globals.css";
import Navber from "@/components/shared/Navber";
import Footer from "@/components/shared/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Car Doctor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme='carDoctortheme'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased mx-auto container`}
      >
        <Navber/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
